"use client";

import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/context/AuthProvider";
import { CssBaseline, ThemeProvider } from "@mui/material";
import Topbar from "@/components/Topbar";
import Sidebar from "@/components/Sidebar";
import { ColorModeContext, useMode } from "./theme";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [theme, colorMode] = useMode();
  const [isSideBar, setIsSidebar] = useState(true);

  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <ColorModeContext.Provider value={colorMode}>
            <ThemeProvider theme={theme}>
              <CssBaseline />
              <div className="app">
                <Sidebar isSideBar={isSideBar} />
                <div className="content">
                  <Topbar setIsSidebar={setIsSidebar} />
                  {children}
                </div>
              </div>
            </ThemeProvider>
          </ColorModeContext.Provider>
        </AuthProvider>
      </body>
    </html>
  );
}
